# Accessing, Deleting and Inserting elements into Array

NumPy ndarrays are mutable, i.e the elements in ndarrays can be changed after the ndarray has been created. NumPy ndarrays can also be sliced, which means that ndarrays can be split in many different ways. This allows us, for example, to retrieve any subset of the ndarray that we want.

Often in Machine Learning you will use slicing to separate data, as for example when dividing a data set into training, cross validation, and testing sets.

In [1]:
# Import the numpy module
import numpy as np

## Accessed by indexing

NumPy also have provides similar API's that Python's standard list indexing to access the elements.Elements can be accessed using indices inside square brackets, [ ]. 

NumPy allows you to use both positive and negative indices to access elements in the ndarray. 
- Positive indices are used to access elements from the beginning of the array
- Negative indices are used to access elements from the end of the array.

In [2]:
np.random.seed(0)  # seed
ndarray1 = np.random.randint(10, size=6)
ndarray1

array([5, 0, 3, 3, 7, 9])

In [3]:
# Access some elements with positive indices
print ('First Element : ',ndarray1 [0])
print ('Second Element : ',ndarray1 [1])
print ('Last Element : ',ndarray1 [5])
print()
# Access the same elements with negative indices
print ('First Element : ',ndarray1 [-6])
print ('Second Element : ',ndarray1 [-5])
print ('Last Element : ',ndarray1 [-1])

First Element :  5
Second Element :  0
Last Element :  9

First Element :  5
Second Element :  0
Last Element :  9


Notice that to access the first element in the ndarray we have to use the index 0 not 1. Also notice, that the same element can be accessed using both positive and negative indices. 

So positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array.

Similarly, we can also access specific elements of rank 2 ndarrays. To access elements in rank 2 ndarrays we need to provide a comma-separated tuple of indices in the form **[row, column]**. 

In [4]:
np.random.seed(0)  # seed
ndarray2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
ndarray2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [5]:
print('Element at (0,0) :', ndarray2[0,0])
print('Element at (0,1) :', ndarray2[0,1])
print('Element at (2,2) :', ndarray2[2,2])
print('Element at (2,3) :', ndarray2[2,3])

print('Element at (0,0) type :', type(ndarray2 [0,0]))

Element at (0,0) : 5
Element at (0,1) : 0
Element at (2,2) : 7
Element at (2,3) : 6
Element at (0,0) type : <class 'numpy.int32'>


In [6]:
print('Element at (0) :', ndarray2[0])
print('Element at (1) :', ndarray2[0])
print('Element at (2) :', ndarray2[2])

print('Element at (0) type :', type(ndarray2 [0]))

Element at (0) : [5 0 3 3]
Element at (1) : [5 0 3 3]
Element at (2) : [2 4 7 6]
Element at (0) type : <class 'numpy.ndarray'>


In [7]:
ndarray3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
ndarray3

array([[[8, 8, 1, 6, 7],
        [7, 8, 1, 5, 9],
        [8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3]],

       [[8, 1, 3, 3, 3],
        [7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4]],

       [[5, 5, 6, 8, 4],
        [1, 4, 9, 8, 1],
        [1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3]]])

In [8]:
ndarray3 [0]

array([[8, 8, 1, 6, 7],
       [7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [9]:
ndarray3 [0 , 1]

array([7, 8, 1, 5, 9])

In [10]:
ndarray3 [0 , 1, 2]

1

## Modified by indexing 

We can change the elements in rank 1 ndarrays. We do this by accessing the element we want to change and then using the = sign to assign the new value

In [11]:
nd1 = np.array([1,2,3,4,5])
nd1

array([1, 2, 3, 4, 5])

In [12]:
# Change the fourth element in array from 4 to 24
nd1[3] = 24
nd1

array([ 1,  2,  3, 24,  5])

Similarly, we can also modify specific elements of rank 2 ndarrays. To access elements in rank 2 ndarrays we need to provide 2 indices in the form **[row, column]**. 

In [13]:
# Create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
nd2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
nd2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
nd2[0,0] = 100
nd2 

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [15]:
nd3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
nd3

array([[[5, 9, 4, 4, 6],
        [4, 4, 3, 4, 4],
        [8, 4, 3, 7, 5],
        [5, 0, 1, 5, 9]],

       [[3, 0, 5, 0, 1],
        [2, 4, 2, 0, 3],
        [2, 0, 7, 5, 9],
        [0, 2, 7, 2, 9]],

       [[2, 3, 3, 2, 3],
        [4, 1, 2, 9, 1],
        [4, 6, 8, 2, 3],
        [0, 0, 6, 0, 6]]])

In [16]:
nd3 [0 , 1, 2] = 999
nd3

array([[[  5,   9,   4,   4,   6],
        [  4,   4, 999,   4,   4],
        [  8,   4,   3,   7,   5],
        [  5,   0,   1,   5,   9]],

       [[  3,   0,   5,   0,   1],
        [  2,   4,   2,   0,   3],
        [  2,   0,   7,   5,   9],
        [  0,   2,   7,   2,   9]],

       [[  2,   3,   3,   2,   3],
        [  4,   1,   2,   9,   1],
        [  4,   6,   8,   2,   3],
        [  0,   0,   6,   0,   6]]])

## Add elements

We can append values to ndarrays using the **np.append(ndarray, elements, axis)** function. This function appends the given list of elements to ndarray along the specified axis.

In [17]:
# create a rank 1 ndarray 
nd1 = np.array([1, 2, 3, 4, 5])
nd1

array([1, 2, 3, 4, 5])

In [18]:
#append the integer 6 and 7 to x
nd1 = np.append(nd1, [6,7])
nd1

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# create a rank 2 ndarray
nd2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
nd2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# append a new row containing 1,2,3 
nd2_0 = np.append(nd2, [[1,2,3]], axis=0)
nd2_0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [21]:
# append a new column containing 99 and 99
nd2_1 = np.append(nd2,[[99],[99]], axis=1)
nd2_1

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [22]:
# append a new column containing 99 and 99
nd2_1 = np.append(nd2,[[99],[99],[99]], axis=1)
nd2_1

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

Notice that when appending rows or columns to rank 3 ndarrays the rows or columns must have the correct shape, so as to match the shape of the rank 3 ndarray.

## Insert elements

We can insert values to ndarrays using the **np.insert(ndarray, index, elements, axis)** function. This function inserts the given list of elements to ndarray right before the given **index** along the specified **axis**. 

In [23]:
# create a rank 1 ndarray 
nd1 = np.array([1, 2, 3, 4, 5])
nd1

array([1, 2, 3, 4, 5])

In [24]:
# insert the integer 3 and 4 between 2 and 5
nd1 = np.insert(nd1,2,[3,4])
nd1

array([1, 2, 3, 4, 3, 4, 5])

In [25]:
# create a rank 2 ndarray 
nd2 = np.array([[1,2,3],[7,8,9]])
nd2

array([[1, 2, 3],
       [7, 8, 9]])

In [26]:
#Insert a row between the first and last row 
nd_1 = np.insert(nd2,1,[4,5,6],axis=0)
nd_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Insert a column full of 5s between the first and second column of y
nd_2 = np.insert(nd2,1,5, axis=1)
nd_2

array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

## Delete elements

We can delete elements using the **np.delete(ndarray, elements, axis)** function.This function deletes the given list of elements from the given ndarray along the specified axis. 

- For rank 1 ndarrays the axis keyword is not required. 
- For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns. 

In [28]:
# create a rank 1 ndarray 
nd1 = np.array([1, 2, 3, 4, 5])
nd1

array([1, 2, 3, 4, 5])

In [29]:
# delete the first and last element
nd1 = np.delete(nd1, [0,4])
nd1

array([2, 3, 4])

In [30]:
# create a rank 2 ndarray
nd2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
nd2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# delete the first row
nd2_0 = np.delete(nd2, 0, axis = 0 )
nd2_0

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
# delete the first and last column
nd2_1 = np.delete(nd2, [0,2], axis = 1 )
nd2_1

array([[2],
       [5],
       [8]])

## Stack Arrays

NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. 

The stacking is done using either the **np.vstack()** function for vertical stacking, or the **np.hstack()** function for horizontal stacking. 

**Note:** In order to stack ndarrays, the shape of the ndarrays must match.

In [33]:
# create a rank 1 ndarray 
x = np.array([1,2])
x

array([1, 2])

In [34]:
#create a rank 2 ndarray 
y = np.array([[3,4],[5,6]])
y

array([[3, 4],
       [5, 6]])

In [35]:
#stack x on top of y
v = np.vstack((x,y))
v

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# stack x on the right of y. We need to reshape x in order to stack it on the right of Y. 
h = np.hstack((y,x.reshape(2,1)))
h

array([[3, 4, 1],
       [5, 6, 2]])