# Arithmetic Operations and Broadcasting on ndarray

NumPy does arithmetic operations on ndarrays. NumPy allows element-wise operations on ndarrays as well as matrix operations.

NumPy sometimes uses something called Broadcasting. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.


Perform element-wise addition, subtraction, multiplication, and division, between ndarrays. To do this, NumPy provides a functional approach, where we use functions such as np.add(), or by using arithmetic symbols, such as +, that resembles more how we write mathematical equations. 

Both forms will do the same operation, the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [1]:
import numpy as np

In [2]:
# create two rank 1 ndarrays
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
y = np.array([5.5,6.5,7.5,8.5])
y

array([5.5, 6.5, 7.5, 8.5])

Perfrom basic element-wise operations using arithmetic symbols and function

In [4]:
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]


In [5]:
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]


In [6]:
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]


In [7]:
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [8]:
X = np.array([1,2,3,4]).reshape(2,2)
X

array([[1, 2],
       [3, 4]])

In [9]:
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
Y

array([[5.5, 6.5],
       [7.5, 8.5]])

Perform basic element-wise operations using arithmetic symbols and functions

In [10]:
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]



In [11]:
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]



In [12]:
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]



In [13]:
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


## Add a number 
NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [14]:
# create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [15]:
3 + X

array([[4, 5],
       [6, 7]])

In [16]:
3 * X

array([[ 3,  6],
       [ 9, 12]])

In [17]:
X / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [18]:
X -3

array([[-2, -1],
       [ 0,  1]])

In the examples above, NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape. This allows us to add 3 to each element of X with just one line of code.

Subject to certain constraints, Numpy can do the same for two ndarrays of different shapes, as we can see below:

In [19]:
# create a rank 1 ndarray
x = np.array([1,2,3])
x

array([1, 2, 3])

In [20]:
# create a 3 x 3 ndarray
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# create a 3 x 1 ndarray
z = np.array([1,2,3]).reshape(3,1)
z

array([[1],
       [2],
       [3]])

In [22]:
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [23]:
z + y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

As before, NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous.

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

In [24]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

np.ones((4,4)) * np.arange(1,5)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## Mathematical Functions
We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.

In [25]:
# create a rank 1 ndarray
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [26]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [27]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [28]:
np.power(x,2)

array([ 1,  4,  9, 16], dtype=int32)

## Statistical Functions

Another great feature of NumPy is that it has a wide variety of statistical functions. Statistical functions provide us with statistical information about the elements in an ndarray.

In [29]:
# create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [30]:
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]


In [31]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]


In [32]:
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]


In [33]:
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [34]:
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]


In [35]:
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]
