In [1]:
import numpy as np

## Boolean indexing

Using indices, slices and select elements of an ndarray. However, there are many situations in which we don't know the indices of the elements that we want to select. 

For example, suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to select those integers that are less than 20. 

Using Boolean indexing can help us in these cases, by allowing us select elements using logical arguments instead of explicit indices.

In [2]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
num = np.arange(25).reshape(5, 5)
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
# Get the elements in 'num' that are greater than 10
num[num > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
# Get the elements in 'num' that less than or equal to 7
num[num <= 7]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
# Get the elements in 'num' that are between 7 and 10
num[(num > 7) & (num < 10)]

array([8, 9])

In [6]:
# Assign the elements that are between 7 and 10 with the value of -1
num[(num > 7) & (num < 10)] = -1
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7, -1, -1],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
odd_nums = num[num % 2 != 0]
odd_nums

array([ 1,  3,  5,  7, -1, -1, 11, 13, 15, 17, 19, 21, 23])