# NumPy

- **NumPy** stands for Numerical Python.It is the fundamental package for scientific computing with Python.
- It provides a high-performance N-dimensional array object, and function for working with these arrays.
- Best suited for working with homogeneous numerical array data.
- It provides Python with an extensive math library capable of performing numerical computations effectively and efficiently.
- It is useful for the linear algebra, Fourier transform, and random number capabilities

In [2]:
# Import the numpy module
import numpy as np

# Creating NumPy Array (N-Dimentional Array)

An array class in Numpy is called as ndarray. All the elements in the ndarray will be same type.

Numpy can be created by multiple ways, By using 'array' function we can create ndarray , it accepts sequence-like object (list, tuple, array) and produces a new NumPy array containing the passed data and either by inferring a dtype or explicitly specifying a dtype; copies the input data by default.

## Creating array with Python List

In [2]:
ndarray1 = np.array([1,25,65,78,56])
print(ndarray1)
print(ndarray1.dtype)

[ 1 25 65 78 56]
int32


## Creating array with Python List of Lists

In [3]:
plist = [[1,25,65,78,56], [1,2,3,4,5]]
print(plist)
ndarray2 = np.array(plist)
print(ndarray2)
print(ndarray2.dtype)

[[1, 25, 65, 78, 56], [1, 2, 3, 4, 5]]
[[ 1 25 65 78 56]
 [ 1  2  3  4  5]]
int32


## Creating array with Python Tuples

In [4]:
pTuple = (1,25,65,78,56)
ndarray3 = np.array(pTuple)
print(ndarray3)
print(ndarray3.dtype)

[ 1 25 65 78 56]
int32


## Creating array with Python Tuples by explicitly specifying a dtype

In [5]:
pTuple = (1,25,65,78,56)
ndarray4 = np.array(pTuple,dtype=np.float64)
print(ndarray4)
print(ndarray4.dtype)

[ 1. 25. 65. 78. 56.]
float64


## Creating ndarray with default values

np.ones() and np.zeros() have an option to specify the data type.

In [6]:
# Create ndarray with zero's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create ndarray with zero's in n dimentional by passing a tuple for the shape.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Create ndarray with zero's in n dimentional by passing a tuple for the shape and dtype.
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [9]:
# Create ndarray with one's with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# Create ndarray with one's in n dimentional by passing a tuple for the shape.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Create an array with initializing its values to a particular value

 np.full() have to specify the constant value that you want to insert into the array.

In [11]:
# Create 2-dimentional array with value 7
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

## Creates an array without initializing its values to any particular value.

In [12]:
# crate 3X3 array without any values
np.empty((3,3,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.78019082e-306],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306]],

       [[2.22522597e-306, 6.23053614e-307],
        [1.33511562e-306, 6.89805151e-307],
        [8.90111708e-307, 2.56765117e-312]]])

## Create an array of evenly-spaced values

np.linspace() and np.arange() can make arrays of evenly spaced values

In [13]:
# Create an array start with 10 increment by 5 and end with 50 
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Creating ndarray with range values like Python range() function.

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create any with Boolean Arrays

In [16]:
bools = np.array([False, False, True, False])
bools

array([False, False,  True, False])

In [17]:
# 'any' checks whether one or more values in an array is True
bools.any()

True

In [18]:
# 'all' checks if every value is True
bools.all()

False

Note: These methods also work with non-boolean arrays, where non-zero elements evaluate to True.

## Create an array with random values

Function **np.random.random(shape)** to create an ndarray of the given shape with random floats in the half-open interval **(0.0, 1.0)**.

In [19]:
np.random.random((2,2))

array([[0.10590887, 0.76491517],
       [0.04503641, 0.1807992 ]])

NumPy also allows us to create ndarrays with random integers within a particular interval. The function **np.random.randint(start, stop, size = shape)** creates an ndarray of the given *shape* with random integers in the half-open interval *(start, stop)*. 

In [16]:
rarray = np.random.randint(2,15,size=(3,2))
rarray

array([[12,  8],
       [ 7, 14],
       [13, 11]])

In [17]:
print('Dimensions:', rarray.shape)
print('Object of type:', type(rarray))
print('Elements of type:', rarray.dtype)

Dimensions: (3, 2)
Object of type: <class 'numpy.ndarray'>
Elements of type: int32


In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. 

For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions.

By using the function **np.random.normal(mean, standard deviation, size=shape)**

For example, creates an ndarray with the given shape that contains random numbers picked from a *normal (Gaussian)* distribution with the given *mean* and *standard deviation*. 


In [20]:
# Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn 
# from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

nums = np.random.normal(0, 0.1, size=(1000,1000))
nums

array([[-0.18048611,  0.02804235,  0.05389984, ..., -0.00597706,
        -0.16555048,  0.02014393],
       [ 0.07779765,  0.00113882, -0.07404905, ..., -0.00437691,
         0.04941652, -0.08304697],
       [-0.12425714, -0.08301533, -0.1359144 , ..., -0.07471323,
        -0.07817098,  0.02837429],
       ...,
       [ 0.13132879,  0.01874828,  0.04920644, ..., -0.05312071,
        -0.07273674,  0.07840716],
       [ 0.07446083,  0.08551189, -0.05680143, ..., -0.0367766 ,
         0.05779505,  0.23747451],
       [ 0.15451875, -0.02452711, -0.16265372, ..., -0.01547021,
         0.14307542,  0.09793187]])

In [22]:
print('Dimensions:', nums.shape)
print('Object of type:', type(nums))
print('Elements of type:', nums.dtype)
print('Mean :', nums.mean())
print('Maximum value:', nums.max())
print('Minimum value:', nums.min())
print('nums has', (nums < 0).sum(), 'negative numbers')
print('nums has', (nums > 0).sum(), 'positive numbers')

Dimensions: (1000, 1000)
Object of type: <class 'numpy.ndarray'>
Elements of type: float64
Mean : 4.358867197292397e-05
Maximum value: 0.45919414925738994
Minimum value: -0.4567179998015289
nums has 500154 negative numbers
nums has 499846 positive numbers


*As we can see, the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in 'num' are symmetric about zero (the average), and we have about the same amount of positive and negative numbers.*

## Create an array with random values, with seed value

In [20]:
np.random.seed(0)  # seed value

np1 = np.random.randint(10, size=6)  # One-dimensional array
np2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
np3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [21]:
np1

array([5, 0, 3, 3, 7, 9])

In [22]:
np2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
np3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

## Creating ndarray with range values like Python range() function.

NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments. 

When used with only one argument, np.arange(N) will create a rank 1 ndarray with consecutive integers between 0 and N - 1. Therefore, notice that if I want an array to have integers between 0 and 9, I have to use N = 10, NOT N = 9

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

When used with two arguments, *np.arange(start,stop)* will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop). This means the evenly spaced numbers will include start but exclude stop. 

In [5]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
r1 = np.arange(4,10)
r1

array([4, 5, 6, 7, 8, 9])

Here, it generates a sequence of integers with 4 inclusive and 10 exclusive.

In [8]:
print('x has dimensions:', r1.shape)
print('x is an object of type:', type(r1))
print('The elements in x are of type:', r1.dtype) 

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


When used with three arguments, np.arange(start,stop,step) will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop) with step being the distance between two adjacent values. 

In [10]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 15 in steps of 3.
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

We can see that here sequential integers between 1 and 15 but the difference between all adjacent values is 3.

**Note:**
Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function **np.linspace()**. 

The np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values.

In [11]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
np.linspace(0,25,10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

The function **np.linspace(0,25,10)** returns an ndarray with 10 evenly spaced numbers in the closed interval [0, 25]. We can also see that both the start and end points, 0 and 25 in this case, are included. However, you can let the endpoint of the interval be excluded (just like in the np.arange() function) by setting the keyword **endpoint = False** in the np.linspace() function.

In [12]:
np.linspace(0,25,10, endpoint = False)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

As we can see, because we have excluded the endpoint, the spacing between values had to change in order to fit 10 evenly spaced numbers in the given interval.

## Create an Identitiy matrix or array

An identity matrix is a square matrix of which all elements in the principal diagonal are ones, and all other elements are zeros.

create an identity array or matrix with np.eye() and np.identity() 

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

If desired, the data type can be changed by using the keyword 'dtype'. 

We can also create diagonal matrices by using the np.diag() function. A diagonal matrix is a square matrix that only has values in its main diagonal. The np.diag() function creates an ndarray corresponding to a diagonal matrix , as shown in the example below:

In [3]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
diag_array = np.diag([10,20,30,50])
diag_array

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])