# NumPy

- It is the fundamental package for scientific computing with Python.
- It provides a high-performance N-dimensional array object, and function for working with these arrays.
- Best suited for working with homogeneous numerical array data.
- It is useful for the linear algebra, Fourier transform, and random number capabilities

In [1]:
# Import the numpy module
import numpy as np

# Creating NumPy Array (N-Dimentional Array)

An array class in Numpy is called as ndarray. All the elements in the ndarray will be same type.

Numpy can be created by multiple ways, By using 'array' function we can create ndarray , it accepts sequence-like object (list, tuple, array) and produces a new NumPy array containing the passed data and either by inferring a dtype or explicitly specifying a dtype; copies the input data by default.

## Creating array with Python List

In [2]:
ndarray1 = np.array([1,25,65,78,56])
print(ndarray1)
print(ndarray1.dtype)

[ 1 25 65 78 56]
int32


## Creating array with Python List of Lists

In [3]:
plist = [[1,25,65,78,56], [1,2,3,4,5]]
print(plist)
ndarray2 = np.array(plist)
print(ndarray2)
print(ndarray2.dtype)

[[1, 25, 65, 78, 56], [1, 2, 3, 4, 5]]
[[ 1 25 65 78 56]
 [ 1  2  3  4  5]]
int32


## Creating array with Python Tuples

In [4]:
pTuple = (1,25,65,78,56)
ndarray3 = np.array(pTuple)
print(ndarray3)
print(ndarray3.dtype)

[ 1 25 65 78 56]
int32


## Creating array with Python Tuples by explicitly specifying a dtype

In [5]:
pTuple = (1,25,65,78,56)
ndarray4 = np.array(pTuple,dtype=np.float64)
print(ndarray4)
print(ndarray4.dtype)

[ 1. 25. 65. 78. 56.]
float64


## Creating ndarray with default values

np.ones() and np.zeros() have an option to specify the data type.

In [6]:
# Create ndarray with zero's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create ndarray with zero's in n dimentional by passing a tuple for the shape.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Create ndarray with zero's in n dimentional by passing a tuple for the shape and dtype.
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [9]:
# Create ndarray with one's with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# Create ndarray with one's in n dimentional by passing a tuple for the shape.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Create an array with initializing its values to a particular value

 np.full() have to specify the constant value that you want to insert into the array.

In [11]:
# Create 2-dimentional array with value 7
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

## Creates an array without initializing its values to any particular value.

In [12]:
# crate 3X3 array without any values
np.empty((3,3,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.78019082e-306],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306]],

       [[2.22522597e-306, 6.23053614e-307],
        [1.33511562e-306, 6.89805151e-307],
        [8.90111708e-307, 2.56765117e-312]]])

## Create an array of evenly-spaced values

np.linspace() and np.arange() can make arrays of evenly spaced values

In [13]:
# Create an array start with 10 increment by 5 and end with 50 
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Creating ndarray with range values like Python range() function.

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create any with Boolean Arrays

In [16]:
bools = np.array([False, False, True, False])
bools

array([False, False,  True, False])

In [17]:
# 'any' checks whether one or more values in an array is True
bools.any()

True

In [18]:
# 'all' checks if every value is True
bools.all()

False

Note: These methods also work with non-boolean arrays, where non-zero elements evaluate to True.

## Create an array with random values

In [19]:
np.random.random((2,2))

array([[0.10590887, 0.76491517],
       [0.04503641, 0.1807992 ]])

## Create an array with random values, with seed value

In [20]:
np.random.seed(0)  # seed value

np1 = np.random.randint(10, size=6)  # One-dimensional array
np2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
np3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [21]:
np1

array([5, 0, 3, 3, 7, 9])

In [22]:
np2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
np3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

## Creating ndarray with range values like Python range() function.

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Create an Identitiy matrix or array

An identity matrix is a square matrix of which all elements in the principal diagonal are ones, and all other elements are zeros.

create an identity array or matrix with np.eye() and np.identity() 

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])