# Joining Arrays
Joining of two arrays in NumPy can be done by using the functions np.concatenate, np.vstack, and np.hstack. np.concatenate with a tuple or list of arrays as its first argument.

In [1]:
# Import the numpy module
import numpy as np

In [5]:
x = np.ones(4, dtype=np.int16)
y = np.arange(1,5,1)

In [6]:
print('x : ',x)
print('y : ',y)

x :  [1 1 1 1]
y :  [1 2 3 4]
z :  [[0 1 2 3]
 [4 5 6 7]]


In [7]:
# Concatenate x and y
np.concatenate((x,y))

array([1, 1, 1, 1, 1, 2, 3, 4])

In [8]:
# More than one array also be concatenated
np.concatenate((x,y,x))

array([1, 1, 1, 1, 1, 2, 3, 4, 1, 1, 1, 1])

In [9]:
z = np.arange(8).reshape((2, 4))
print('z : ',z)

z :  [[0 1 2 3]
 [4 5 6 7]]


In [10]:
# concatenate along the first axis
np.concatenate((z,z))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
# concatenate along the second axis (zero-indexed)
np.concatenate([z, z], axis=1)

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

#### np.vstack (vertical stack) and np.hstack (horizontal stack) functions are to be used when working with different dimentions.

In [14]:
print('x : ', x)
print('y : ', y)
print('z : ', z)

x :  [1 1 1 1]
y :  [1 2 3 4]
z :  [[0 1 2 3]
 [4 5 6 7]]


In [12]:
# Stack arrays vertically 
np.vstack((y, z))

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
np.vstack((x,y))

array([[1, 1, 1, 1],
       [1, 2, 3, 4]])

In [17]:
# Stack arrays horizontally
np.hstack((x,y))

array([1, 1, 1, 1, 1, 2, 3, 4])

In [18]:
# Stack arrays column-wise
np.column_stack((x,y))

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

# Split Arrays
Split Arrays by calling the functions np.split, np.hsplit, and np.vsplit with parameters as array and list of indices for the split points

In [19]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, x4 = np.split(x, [3, 5, 8])
print(x1, x2, x3, x4)

[1 2 3] [4 5] [6 7 8] [9]


In [20]:
ndarray = np.arange(9).reshape((3, 3))
ndarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
upper, lower = np.vsplit(ndarray, [1])
print(upper)
print(lower)

[[0 1 2]]
[[3 4 5]
 [6 7 8]]


In [22]:
upper, lower = np.vsplit(ndarray, [2])
print(upper)
print(lower)

[[0 1 2]
 [3 4 5]]
[[6 7 8]]


In [23]:
left, right = np.hsplit(ndarray, [1])
print(left)
print(right)

[[0]
 [3]
 [6]]
[[1 2]
 [4 5]
 [7 8]]


In [24]:
left, right = np.hsplit(ndarray, [2])
print(left)
print(right)

[[0 1]
 [3 4]
 [6 7]]
[[2]
 [5]
 [8]]


# Transposing Arrays

In [25]:
ndarray1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
ndarray1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
ndarray1.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [28]:
np.transpose(ndarray1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])