# Indexing and Slicing

In [1]:
# Import the numpy module
import numpy as np

## Indexing
- NumPy also have provides similar API's that Python's standard list indexing to access the elements.

In [3]:
np.random.seed(0)  # seed
ndarray1 = np.random.randint(10, size=6)
ndarray1

array([5, 0, 3, 3, 7, 9])

In [8]:
print ('@index 0 : ',ndarray1 [0])
print ('@index -3: ',ndarray1 [-3]) # To read from the end of the array, you can use negative index 

@index 0 :  5
@index -3:  3


In [9]:
np.random.seed(0)  # seed
ndarray2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
ndarray2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [10]:
# In case of n-dimensional array, items can be accessed using a comma-separated tuple of indices:
ndarray2 [0,0]

5

In [11]:
ndarray2 [0]

array([5, 0, 3, 3])

In [12]:
ndarray3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
ndarray3

array([[[8, 8, 1, 6, 7],
        [7, 8, 1, 5, 9],
        [8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3]],

       [[8, 1, 3, 3, 3],
        [7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2],
        [7, 2, 0, 0, 4]],

       [[5, 5, 6, 8, 4],
        [1, 4, 9, 8, 1],
        [1, 7, 9, 9, 3],
        [6, 7, 2, 0, 3]]])

In [13]:
ndarray3 [0]

array([[8, 8, 1, 6, 7],
       [7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [14]:
ndarray3 [0 , 1]

array([7, 8, 1, 5, 9])

In [15]:
ndarray3 [0 , 1, 2]

1

Values can also be modified using index and value is of the same type.

In [17]:
ndarray3 [0 , 1, 2] = 999
ndarray3

array([[[  8,   8,   1,   6,   7],
        [  7,   8, 999,   5,   9],
        [  8,   9,   4,   3,   0],
        [  3,   5,   0,   2,   3]],

       [[  8,   1,   3,   3,   3],
        [  7,   0,   1,   9,   9],
        [  0,   4,   7,   3,   2],
        [  7,   2,   0,   0,   4]],

       [[  5,   5,   6,   8,   4],
        [  1,   4,   9,   8,   1],
        [  1,   7,   9,   9,   3],
        [  6,   7,   2,   0,   3]]])

## Slicing:

- a[start:end]   # items start through the end (but the end is not included!)
- a[start:]      # items start through the rest of the array
- a[:end]        # items from the beginning through the end (but the end is not included!)

In [19]:
ndarray1

array([5, 0, 3, 3, 7, 9])

In [20]:
ndarray1[2:6]

array([3, 3, 7, 9])

In [24]:
ndarray1[:4] # Get list with first 4 elements

array([5, 0, 3, 3])

In [25]:
ndarray1[2:] # Get list with elements after index 2

array([3, 3, 7, 9])

In [26]:
ndarray1[::2]  # every other element

array([5, 3, 7])

In [27]:
ndarray1[0::2]  # every other element, from index 1

array([5, 3, 7])

In [28]:
ndarray1[::-1]  # all elements, reversed

array([9, 7, 3, 3, 0, 5])

In [29]:
ndarray1[5::-2]  # reversed every other from index 5

array([9, 3, 0])

In [30]:
ndarr_slice = ndarray1[2:6]
ndarr_slice

array([3, 3, 7, 9])

In [31]:
print('Before update : ', ndarray1)
# Any change in values of the slice array , the mutations are reflected in the original array
ndarr_slice[1] = 24
print('After update : ', ndarray1)

Before update :  [5 0 3 3 7 9]
After update :  [ 5  0  3 24  7  9]


Note: In other programming languges, data is copied to new variable, but here is not. Since NumPy is designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

#### Creating copies of arrays
If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array.

In [44]:
ndarray1 = np.random.randint(20, size=10)
ndarr_slice = ndarray1[2:6].copy()

In [45]:
print('Before update : ndarray1 = ', ndarray1)
print('Before update : ndarr_slice =', ndarr_slice)

Before update : ndarray1 =  [ 9  1  4 10 11  8 11  2 19 16]
Before update : ndarr_slice = [ 4 10 11  8]


In [46]:
ndarr_slice[1] = 1111

In [47]:
print('After update : ndarray1 = ', ndarray1)
print('After update : ndarr_slice =', ndarr_slice)

After update : ndarray1 =  [ 9  1  4 10 11  8 11  2 19 16]
After update : ndarr_slice = [   4 1111   11    8]


#### N-Dimentional Array

In [48]:
ndarray2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
ndarray2

array([[0, 6, 0, 6],
       [3, 3, 8, 8],
       [8, 2, 3, 2]])

In [53]:
ndarray2[:2, :3]  # two rows, four columns

array([[0, 6, 0],
       [3, 3, 8]])

In [54]:
ndarray2[:3, ::2]  # all rows, every other column

array([[0, 0],
       [3, 8],
       [8, 3]])

In [55]:
ndarray2[:,:2] # all rows, 2 column

array([[0, 6],
       [3, 3],
       [8, 2]])

In [56]:
ndarray2[0,:2] # one rows, 2 column

array([0, 6])

#### Accessing single rows or columns of an array

This can be done by combining indexing and slicing as below:

In [59]:
ndarray2

array([[0, 6, 0, 6],
       [3, 3, 8, 8],
       [8, 2, 3, 2]])

In [61]:
print('First Column of the ndarray : ',ndarray2[:, 0])  # first column of ndarray
print('First Row of the ndarray : ',ndarray2[0, :])  # first row of ndarray
print('First Row of the ndarray : ',ndarray2[0]) # while accessing rows the empty slice can be omitted.

First Column of the ndarray :  [0 3 8]
First Row of the ndarray :  [0 6 0 6]
First Row of the ndarray :  [0 6 0 6]
