# Reshape and Resize NumPy Array

Reshaping and Resizing an array by using reshape() and resize() methods

In [1]:
# Import the numpy module
import numpy as np

In [2]:
# Creating an array from 0 to 9 
ndarray1 = np.arange(9)
ndarray1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshaping the array to 3×3 grid by using reshape() 

In [5]:
ndarray1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### Note: Size of the initial array must match the size of the reshaped array. 

In [4]:
ndarray1.reshape((9, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [6]:
np.random.seed(0)  # seed
ndarray2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
ndarray2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [8]:
# np.resize() function accepts array and new dimentions
np.resize(ndarray2,(6,4))

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

#### Flatten 

In [9]:
ndarray2.ravel()

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6])

#### Swapping Axes

In [10]:
ndarray3 = np.random.randint(10, size=(3, 5))  # Two-dimensional array
ndarray3

array([[8, 8, 1, 6, 7],
       [7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0]])

In [11]:
ndarray2.swapaxes(0,1)

array([[5, 7, 2],
       [0, 9, 4],
       [3, 3, 7],
       [3, 5, 6]])

In [13]:
ndarray3.swapaxes(1,0)

array([[8, 7, 8],
       [8, 8, 9],
       [1, 1, 4],
       [6, 5, 3],
       [7, 9, 0]])