In [2]:
import numpy as np

## Q48. Write the NumPy program to create a 2d array with 6 on the border and 0 inside?

In [4]:
n = np.full((5,5),6)
print("Original array-")
print(n)

n[1:-1,1:-1] = 0
print('6 on the border and 0 inside in the array-')
print(n)

Original array-
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array-
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


## Q49. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern?

In [8]:
n = np.full((8,8),3)
#print(n)
print('Checkerboard pattern-')

n[1::2,::2] = 9
#print(n)
n[::2,1::2] = 9
print(n)

Checkerboard pattern-
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


## Q50. Write the NumPy program to create an empty and a full array.

In [12]:
print('Create an empty array')
e = np.empty((4,3))
print(e)

print('\nCreate a full array')
f = np.full((2,3),2)
print(f)

Create an empty array
[[9.82723989e-312 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.58817677e-052]
 [5.64164656e-091 1.77102547e-051 3.61054305e+174]
 [3.11088268e+179 3.99910963e+252 1.46030983e-319]]

Create a full array
[[2 2 2]
 [2 2 2]]


## Q51. Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

In [14]:
# if the input is Centigrad values

array = [0, 12, 45.21, 34, 99.91]
c = np.array(array)
print('Values in Centigrad degrees-')
print(c)

print('Values in Fahrenheit degrees-')
f = (9 * c +(32*5)) / 5
print(f)

Values in Centigrad degrees-
[ 0.   12.   45.21 34.   99.91]
Values in Fahrenheit degrees-
[ 32.     53.6   113.378  93.2   211.838]


In [15]:
# if the input is Fahrenheit values

array = [0, 12, 45.21, 34, 99.91]
f = np.array(array)
print('Values in Fahrenheit degrees-')
print(f)

print('Values in Centigrad degrees-')
c = (5 * (f-32)) / 9
print(c)

Values in Fahrenheit degrees-
[ 0.   12.   45.21 34.   99.91]
Values in Centigrad degrees-
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
